In [3]:
import numpy as np

def isDiagonallyDominant(x):

    x = np.array(x)

    diag = np.diag(np.abs(x))

    off_diag = np.sum(np.abs(x), axis = 1) - diag

    if np.all(diag > off_diag):
        return True
    else:
        return False 
    
def gauss_seidel(x, y, epsilon = 0.01, t = 15):
    if not isDiagonallyDominant(x):
        print('is not diagonally dominant')
        return
    
    x = np.array(x)
    y = np.array(y)

    #mengambil nilai diagonal
    diag = np.diag(np.abs(x))

    #negasi nilai x
    x = -x

    #ngisi diagonalnya dengan 0
    np.fill_diagonal(x, 0)

    mtx_old = np.zeros(x[0].shape)

    #dia bakal ngukur sesuai dengan batas iterasi
    for i in range(t):
        mtx_new = np.array(mtx_old)
        #mengisi/menghitung setiap data iterasi
        for idx, row in enumerate(x):
            mtx_new[idx] = (y[idx] + np.dot(row, mtx_new)) / diag[idx]

        print(f'iterasi ke - {i}')
        print(mtx_new)

        dx = np.sqrt(np.dot(mtx_new - mtx_old, mtx_new - mtx_old))
        print(f'dx : -{dx}')

        if dx < epsilon:
            print('converged')
            return
        
        mtx_old = mtx_new

    print('not converged')
    return

Xs = [[10, 4, 5],
      [1, 6, 1],
      [3, 1, 6]]

Ys = [8, 5, 10]

gauss_seidel(Xs, Ys)


iterasi ke - 0
[0.8  0.7  1.15]
dx : -1.5660459763365826
iterasi ke - 1
[-0.055       0.65083333  1.58569444]
dx : -0.9608704439365717
iterasi ke - 2
[-0.25318056  0.61124769  1.69138233]
dx : -0.22806245930668492
iterasi ke - 3
[-0.29019024  0.59980132  1.7117949 ]
dx : -0.04378822902864041
iterasi ke - 4
[-0.29581798  0.59733718  1.71501946]
dx : -0.006938385517329205
converged
