In [6]:
import numpy as np

# np.array

list1 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

array1 = np.array(list1)

array2 = np.array([-3, 4, 7, -10, 2, 123, 56])

print(array2)

# print(array1)

# print(np.shape(array1))

print(np.ndim(array1))

zeros = np.zeros(10)
print(zeros)

ones = np.ones(10)
print(ones)

empty = np.empty(10)
print(empty)

print(np.arange(10))

#np.sum(array2)

#np.min(array2)

#print(np.cumsum(array2))

#np.reshape(ones, (2,5))

matrix_x  = [[1,2,3],
             [4,5,6],
             [7,8,9]]

matrix_y = [[5,2,3],
            [3,3,10],
            [7,2,9]]


#print(np.dot(matrix_x, matrix_y))

#print(np.abs(array2))

#print(np.diag(matrix_x))

#print(np.sign(-12))



[ -3   4   7 -10   2 123  56]
2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
